# This file is auto-generated by GitHub Actions
# Manual edits will be overwritten on next release

class QuickcodeCli < Formula
  desc "QuickCode API CLI tool"
  homepage "https://github.com/QuickCodeNet/quickcode.cli"
  url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.2/quickcode-cli-osx-arm64-v1.0.2.tar.gz"
  sha256 "c5ba61767bb4954191d55149dc3c6090f684faad6cdef095c54fec6aaa09bd18"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.2/quickcode-cli-osx-arm64-v1.0.2.tar.gz"
      sha256 "c5ba61767bb4954191d55149dc3c6090f684faad6cdef095c54fec6aaa09bd18"
    else
      url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.2/quickcode-cli-osx-x64-v1.0.2.tar.gz"
      sha256 "fbb4f7932b52e71cc8ac8c5b95778f72b7f3b0bd6ef81dc039012b13f1fe2710"
    end
  end

  def install
    bin.install "quickcode"
  end

  test do
    system "#{bin}/quickcode", "--version"
  end
end
