# This file is auto-generated by GitHub Actions
# Manual edits will be overwritten on next release

class QuickcodeCli < Formula
  desc "QuickCode API CLI tool"
  homepage "https://github.com/QuickCodeNet/quickcode.cli"
  url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.21/quickcode-cli-osx-arm64-v1.0.21.tar.gz"
  sha256 "49d8d6aac7f1fda3512ef0b2c1371c249697e07c140c473176c33cdc6f54d4c0"
  version "1.0.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.21/quickcode-cli-osx-arm64-v1.0.21.tar.gz"
      sha256 "49d8d6aac7f1fda3512ef0b2c1371c249697e07c140c473176c33cdc6f54d4c0"
    else
      url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.21/quickcode-cli-osx-x64-v1.0.21.tar.gz"
      sha256 "d37845a329386932f4636fd50fcc3a4688a372260f785f2d4f4a5332f96fd701"
    end
  end

  def install
    bin.install "quickcode"
  end

  test do
    system "#{bin}/quickcode", "--version"
  end
end
