# This file is auto-generated by GitHub Actions
# Manual edits will be overwritten on next release

class QuickcodeCli < Formula
  desc "QuickCode API CLI tool"
  homepage "https://github.com/QuickCodeNet/quickcode.cli"
  url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.36/quickcode-cli-osx-arm64-v1.0.36.tar.gz"
  sha256 "618813744caffaaff9c0e0f1be658356a33ad1c8c834544fa8d3aa15a2fe4c32"
  version "1.0.36"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.36/quickcode-cli-osx-arm64-v1.0.36.tar.gz"
      sha256 "618813744caffaaff9c0e0f1be658356a33ad1c8c834544fa8d3aa15a2fe4c32"
    else
      url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.36/quickcode-cli-osx-x64-v1.0.36.tar.gz"
      sha256 "9d81822f94c29832901c2f4cefea1f1de1a0b964c2efd24065bcae8c01e7584d"
    end
  end

  def install
    bin.install "quickcode"
  end

  test do
    system "#{bin}/quickcode", "--version"
  end
end
